alias gcc="gcc -ansi -Wall -g -O0 -Wwrite-strings -Wshadow -pedantic-errors -fstack-protector-all"
alias du="du -h"
alias-append ls "-h"
alias ulimit="ulimit -S"
alias vim="vim --servername vim"
alias to-clipboard="xclip -sel clip"
