#!/usr/bin/env bash
export EDITOR=vim
export GOPATH="$HOME/go"
export BASH_COMPLETION_USER_DIR=~/bashrc.d/

add_to_path() {
    if [[ -d $1 && :$PATH != *:$1* ]]; then
        PATH="$1:$PATH"
    fi
}

add_to_path "$HOME/bin"
add_to_path "$HOME/scripts"
add_to_path "$HOME/.local/bin"
add_to_path "$HOME/.cargo/bin"
add_to_path "$GOPATH/bin"
add_to_path "/usr/local/go/bin"

__bashrc_cleanup+=("add_to_path")
